name: flutter_navigation_generator_animations
description: Generate your Flutter navigator by annotating your screen 
version: 1.1.0+experimental
homepage: https://github.com/ikbendewilliam/flutter_navigation_generator
repository: https://github.com/ikbendewilliam/flutter_navigation_generator
issue_tracker: https://github.com/ikbendewilliam/flutter_navigation_generator/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies: 
  flutter:
    sdk: flutter
